# Permalinks
permalink:           pretty

# Setup
title:               Luiz Assunção
tagline:             'A blog about software development'
description:         'Made by <a href="https://twitter.com/LuizHAssuncao" target="_blank">@LuizHAssuncao</a>.'
url:                 https://www.luiz.tech
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Luiz Assunção
  url:               https://twitter.com/LuizHAssuncao
  email:             luizhenrique.assuncao@gmail.com

# Custom vars
version:             1.0.0

# Plugins
plugins: [jekyll-paginate]
