# Permalinks
permalink:           blog/:year/:month/:day/:title/

# Setup
title:               Luiz Assunção
tagline:             'About software engineering'
description:         'Made by <a href="https://twitter.com/LuizHAssuncao" target="_blank">Luiz Assunção</a>'
url:                 https://www.luiz.tech
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Luiz Assunção
  url:               https://twitter.com/LuizHAssuncao
  email:             me@luiz.tech

# Custom vars
version:             1.0.0

# Plugins
plugins: [jekyll-paginate]

## My Variables

# Personal Information
email:                me@luiz.tech

# Social Nicknames
linkedin_username:    LuizHAssuncao
twitter_username:     luizhassuncao
github_username:      luizhassuncao

# Excerpt configuration
excerpt_separator: <!--more-->
